name: 'Pull Request Comment Branch'

description: 'Gets the head ref and sha of a pull request comment'

author: 'Madrona Games, Inc.'

branding:
  icon: 'message-square'
  color: 'white'

inputs:
  repo-token:
    description: 'GITHUB_TOKEN token or a repo scoped PAT'
    required: true
    default: ${{ github.token }}

outputs:
  base-ref:
    description: 'The name of the branch the pull request will merge into.'
  base-sha:
    description: 'The head sha of the branch the pull request will merge into.'
  head-ref:
    description: 'The name of the pull request branch the comment belongs to.'
  head-sha:
    description: 'The head sha of the pull request branch the comment belongs to.'

runs:
  using: 'node20'
  main: 'dist/index.js'
