on:
  push:

jobs:
  build:
    runs-on: [self-hosted, linux, small]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Run Build
        run: |
          npm run build

      - name: Check for changes
        run: |
          git diff --quiet --exit-code dist || git commit -am "Update dist folder" && git push
